site_name: radrags
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

nav:
  - Home: index.md
  - Guide:
      - Usage: guide/usage.md
      - Doc-tree Traversal: guide/doc-tree.md
      - Vector Store: guide/vector-store.md
  - API Reference: api/reference.md
